error: calculates the error of an arbitrary expression, given values and errors for each variable in the expression.
Requires working C++ compiler (clang++ by default), runs only on ELF targets, uses dlfcn.h and needs cwd mounted with 'exec'.
Guess why.